/*
* Generated by SGWrapperGen - DO NOT EDIT!
*
* SwinGame wrapper for C - Types
*
* Wrapping sgTypes.pas
*/

#ifndef sgTypes
#define sgTypes

#include <stdint.h>

#ifndef __cplusplus
  #include <stdbool.h>
#endif


typedef int32_t *longint_array;

typedef char **string_array;

typedef float *single_array;

typedef struct _named_index_collection { 
    string_array names;
    void *ids;
} named_index_collection;

typedef struct _point2d { 
    float x;
    float y;
} point2d;

typedef struct _vector { 
    float x;
    float y;
} vector;

typedef point2d *point2d_array;

typedef struct _rectangle { 
    float x;
    float y;
    int32_t width;
    int32_t height;
} rectangle;

typedef struct _finger { 
    long long id;
    point2d position;
    point2d position_delta;
    point2d last_position;
    float pressure;
    bool down;
} finger;

typedef finger *finger_array;

typedef struct _resolution { 
    unsigned short int format;
    int32_t refresh_rate;
    int32_t width;
    int32_t height;
} resolution;

typedef resolution *resolution_array;

typedef struct _circle { 
    point2d center;
    int32_t radius;
} circle;

typedef struct _accelerometer_motion { 
    int32_t x_axis;
    int32_t y_axis;
    int32_t z_axis;
} accelerometer_motion;

typedef struct _line_segment { 
    point2d start_point;
    point2d end_point;
} line_segment;

typedef struct _triangle { 
    point2d points[3];
} triangle;

typedef line_segment *lines_array;

typedef triangle *triangle_array;

typedef struct _sound_effect_data { 
    void *effect;
    const char *filename;
    const char *name;
} sound_effect_data;

typedef struct _sound_effect_data *sound_effect;

typedef struct _music_data { 
    void *music;
    const char *filename;
    const char *name;
} music_data;

typedef struct _music_data *music;

typedef struct _matrix2d { 
    float elements[3][3];
} matrix2d;

typedef uint32_t color;

typedef struct _animation_frame { 
} animation_frame;

typedef struct _animation_frame_data { 
    int32_t index;
    int32_t cell_index;
    sound_effect_data *sound;
    float duration;
    vector movement;
    void *next;
} animation_frame_data;

typedef struct _animation_script_data { 
    const char *name;
    const char *filename;
    named_index_collection animation_ids;
    int32_t *animations;
    animation_frame *frames;
    void *anim_objs;
    int32_t next_anim_idx;
} animation_script_data;

typedef struct _animation_script_data *animation_script;

typedef struct _animation_data { 
    void *first_frame;
    void *current_frame;
    void *last_frame;
    float frame_time;
    bool entered_frame;
    animation_script_data *script;
    const char *animation_name;
} animation_data;

typedef struct _animation_data *animation;

typedef struct _bitmap_data { 
    const char *filename;
    const char *name;
    void *surface;
    int32_t width;
    int32_t height;
    float texture_width_ratio;
    float texture_height_ratio;
    int32_t cell_w;
    int32_t cell_h;
    int32_t cell_cols;
    int32_t cell_rows;
    int32_t cell_count;
    bool *non_transparent_pixels;
    rectangle *clip_stack;
} bitmap_data;

typedef struct _bitmap_data *bitmap;

typedef bitmap *bitmap_array;

typedef struct _bitmap_cell { 
    bitmap_data *bmp;
    int32_t cell;
} bitmap_cell;

typedef enum { 
    TOP,
    BOTTOM,
    LEFT,
    RIGHT,
    TOP_LEFT,
    TOP_RIGHT,
    BOTTOM_LEFT,
    BOTTOM_RIGHT,
    NONE
} collision_side;

typedef enum { 
    BUNDLE_RESOURCE,
    TIMER_RESOURCE,
    BITMAP_RESOURCE,
    FONT_RESOURCE,
    MUSIC_RESOURCE,
    MAP_RESOURCE,
    SOUND_RESOURCE,
    ANIMATION_RESOURCE,
    PANEL_RESOURCE,
    CHARACTER_RESOURCE,
    OTHER_RESOURCE
} resource_kind;

typedef enum { 
    PIXEL_COLLISIONS,
    AABBCOLLISIONS
} collision_test_kind;

typedef enum { 
    SPRITE_ARRIVED_EVENT,
    SPRITE_ANIMATION_ENDED_EVENT,
    SPRITE_TOUCHED_EVENT,
    SPRITE_CLICKED_EVENT
} sprite_event_kind;

typedef struct _sprite_data *sprite;

typedef void *sprite_event_handler;

typedef void *sprite_function;

typedef void *sprite_single_function;

typedef sprite_event_handler *sprite_event_handler_array;

typedef struct _sprite_data { 
    const char *name;
    named_index_collection layer_ids;
    bitmap *layers;
    int32_t *visible_layers;
    point2d *layer_offsets;
    float *values;
    named_index_collection value_ids;
    animation_data *animation_info;
    animation_script_data *animation_script;
    point2d position;
    vector velocity;
    collision_test_kind collision_kind;
    bitmap_data *collision_bitmap;
    bitmap_data *backup_collision_bitmap;
    bitmap_data *cache_image;
    bool is_moving;
    point2d destination;
    vector moving_vec;
    float arrive_in_sec;
    int32_t last_update;
    bool announced_animation_end;
    sprite_event_handler_array evts;
    void *pack;
} sprite_data;

typedef struct _timer_data { 
    uint32_t start_ticks;
    uint32_t paused_ticks;
    bool paused;
    bool started;
    const char *name;
} timer_data;

typedef struct _timer_data *timer;

typedef struct _font_data { 
    void *fptr;
    const char *name;
} font_data;

typedef struct _font_data *font;

typedef enum { 
    NORMAL_FONT = 0,
    BOLD_FONT = 1,
    ITALIC_FONT = 2,
    UNDERLINE_FONT = 4
} font_style;

typedef enum { 
    ALIGN_LEFT = 1,
    ALIGN_CENTER = 2,
    ALIGN_RIGHT = 4
} font_alignment;

typedef enum { 
    NO_BUTTON,
    LEFT_BUTTON,
    MIDDLE_BUTTON,
    RIGHT_BUTTON,
    WHEEL_UP_BUTTON,
    WHEEL_DOWN_BUTTON,
    MOUSE_X1BUTTON,
    MOUSE_X2BUTTON
} mouse_button;

typedef enum { 
    VK_UNKNOWN = 0,
    VK_BACKSPACE = 8,
    VK_TAB = 9,
    VK_CLEAR = 12,
    VK_RETURN = 13,
    VK_PAUSE = 19,
    VK_ESCAPE = 27,
    VK_SPACE = 32,
    VK_EXCLAIM = 33,
    VK_QUOTEDBL = 34,
    VK_HASH = 35,
    VK_DOLLAR = 36,
    VK_AMPERSAND = 38,
    VK_QUOTE = 39,
    VK_LEFTPAREN = 40,
    VK_RIGHTPAREN = 41,
    VK_ASTERISK = 42,
    VK_PLUS = 43,
    VK_COMMA = 44,
    VK_MINUS = 45,
    VK_PERIOD = 46,
    VK_SLASH = 47,
    VK_0 = 48,
    VK_1 = 49,
    VK_2 = 50,
    VK_3 = 51,
    VK_4 = 52,
    VK_5 = 53,
    VK_6 = 54,
    VK_7 = 55,
    VK_8 = 56,
    VK_9 = 57,
    VK_COLON = 58,
    VK_SEMICOLON = 59,
    VK_LESS = 60,
    VK_EQUALS = 61,
    VK_GREATER = 62,
    VK_QUESTION = 63,
    VK_AT = 64,
    VK_LEFTBRACKET = 91,
    VK_BACKSLASH = 92,
    VK_RIGHTBRACKET = 93,
    VK_CARET = 94,
    VK_UNDERSCORE = 95,
    VK_BACKQUOTE = 96,
    VK_A = 97,
    VK_B = 98,
    VK_C = 99,
    VK_D = 100,
    VK_E = 101,
    VK_F = 102,
    VK_G = 103,
    VK_H = 104,
    VK_I = 105,
    VK_J = 106,
    VK_K = 107,
    VK_L = 108,
    VK_M = 109,
    VK_N = 110,
    VK_O = 111,
    VK_P = 112,
    VK_Q = 113,
    VK_R = 114,
    VK_S = 115,
    VK_T = 116,
    VK_U = 117,
    VK_V = 118,
    VK_W = 119,
    VK_X = 120,
    VK_Y = 121,
    VK_Z = 122,
    VK_DELETE = 127,
    VK_WORLD_0 = 160,
    VK_WORLD_1 = 161,
    VK_WORLD_2 = 162,
    VK_WORLD_3 = 163,
    VK_WORLD_4 = 164,
    VK_WORLD_5 = 165,
    VK_WORLD_6 = 166,
    VK_WORLD_7 = 167,
    VK_WORLD_8 = 168,
    VK_WORLD_9 = 169,
    VK_WORLD_10 = 170,
    VK_WORLD_11 = 171,
    VK_WORLD_12 = 172,
    VK_WORLD_13 = 173,
    VK_WORLD_14 = 174,
    VK_WORLD_15 = 175,
    VK_WORLD_16 = 176,
    VK_WORLD_17 = 177,
    VK_WORLD_18 = 178,
    VK_WORLD_19 = 179,
    VK_WORLD_20 = 180,
    VK_WORLD_21 = 181,
    VK_WORLD_22 = 182,
    VK_WORLD_23 = 183,
    VK_WORLD_24 = 184,
    VK_WORLD_25 = 185,
    VK_WORLD_26 = 186,
    VK_WORLD_27 = 187,
    VK_WORLD_28 = 188,
    VK_WORLD_29 = 189,
    VK_WORLD_30 = 190,
    VK_WORLD_31 = 191,
    VK_WORLD_32 = 192,
    VK_WORLD_33 = 193,
    VK_WORLD_34 = 194,
    VK_WORLD_35 = 195,
    VK_WORLD_36 = 196,
    VK_WORLD_37 = 197,
    VK_WORLD_38 = 198,
    VK_WORLD_39 = 199,
    VK_WORLD_40 = 200,
    VK_WORLD_41 = 201,
    VK_WORLD_42 = 202,
    VK_WORLD_43 = 203,
    VK_WORLD_44 = 204,
    VK_WORLD_45 = 205,
    VK_WORLD_46 = 206,
    VK_WORLD_47 = 207,
    VK_WORLD_48 = 208,
    VK_WORLD_49 = 209,
    VK_WORLD_50 = 210,
    VK_WORLD_51 = 211,
    VK_WORLD_52 = 212,
    VK_WORLD_53 = 213,
    VK_WORLD_54 = 214,
    VK_WORLD_55 = 215,
    VK_WORLD_56 = 216,
    VK_WORLD_57 = 217,
    VK_WORLD_58 = 218,
    VK_WORLD_59 = 219,
    VK_WORLD_60 = 220,
    VK_WORLD_61 = 221,
    VK_WORLD_62 = 222,
    VK_WORLD_63 = 223,
    VK_WORLD_64 = 224,
    VK_WORLD_65 = 225,
    VK_WORLD_66 = 226,
    VK_WORLD_67 = 227,
    VK_WORLD_68 = 228,
    VK_WORLD_69 = 229,
    VK_WORLD_70 = 230,
    VK_WORLD_71 = 231,
    VK_WORLD_72 = 232,
    VK_WORLD_73 = 233,
    VK_WORLD_74 = 234,
    VK_WORLD_75 = 235,
    VK_WORLD_76 = 236,
    VK_WORLD_77 = 237,
    VK_WORLD_78 = 238,
    VK_WORLD_79 = 239,
    VK_WORLD_80 = 240,
    VK_WORLD_81 = 241,
    VK_WORLD_82 = 242,
    VK_WORLD_83 = 243,
    VK_WORLD_84 = 244,
    VK_WORLD_85 = 245,
    VK_WORLD_86 = 246,
    VK_WORLD_87 = 247,
    VK_WORLD_88 = 248,
    VK_WORLD_89 = 249,
    VK_WORLD_90 = 250,
    VK_WORLD_91 = 251,
    VK_WORLD_92 = 252,
    VK_WORLD_93 = 253,
    VK_WORLD_94 = 254,
    VK_WORLD_95 = 255,
    VK_KP0 = 256,
    VK_KP1 = 257,
    VK_KP2 = 258,
    VK_KP3 = 259,
    VK_KP4 = 260,
    VK_KP5 = 261,
    VK_KP6 = 262,
    VK_KP7 = 263,
    VK_KP8 = 264,
    VK_KP9 = 265,
    VK_KP_PERIOD = 266,
    VK_KP_DIVIDE = 267,
    VK_KP_MULTIPLY = 268,
    VK_KP_MINUS = 269,
    VK_KP_PLUS = 270,
    VK_KP_ENTER = 271,
    VK_KP_EQUALS = 272,
    VK_UP = 273,
    VK_DOWN = 274,
    VK_RIGHT = 275,
    VK_LEFT = 276,
    VK_INSERT = 277,
    VK_HOME = 278,
    VK_END = 279,
    VK_PAGEUP = 280,
    VK_PAGEDOWN = 281,
    VK_F1 = 282,
    VK_F2 = 283,
    VK_F3 = 284,
    VK_F4 = 285,
    VK_F5 = 286,
    VK_F6 = 287,
    VK_F7 = 288,
    VK_F8 = 289,
    VK_F9 = 290,
    VK_F10 = 291,
    VK_F11 = 292,
    VK_F12 = 293,
    VK_F13 = 294,
    VK_F14 = 295,
    VK_F15 = 296,
    VK_NUMLOCK = 300,
    VK_CAPSLOCK = 301,
    VK_SCROLLOCK = 302,
    VK_RSHIFT = 303,
    VK_LSHIFT = 304,
    VK_RCTRL = 305,
    VK_LCTRL = 306,
    VK_RALT = 307,
    VK_LALT = 308,
    VK_RMETA = 309,
    VK_LMETA = 310,
    VK_LSUPER = 311,
    VK_RSUPER = 312,
    VK_MODE = 313,
    VK_COMPOSE = 314,
    VK_HELP = 315,
    VK_PRINT = 316,
    VK_SYSREQ = 317,
    VK_BREAK = 318,
    VK_MENU = 319,
    VK_POWER = 320,
    VK_EURO = 321
} key_code;

typedef void *free_notifier;

typedef struct _direction_angles { 
    int32_t min;
    int32_t max;
} direction_angles;

typedef struct _dir_state_data { 
    int32_t anim;
    int32_t *layer_order;
} dir_state_data;

typedef struct _character_data { 
    const char *name;
    const char *file_name;
    sprite_data *char_sprite;
    const char *char_name;
    const char *char_type;
    named_index_collection states;
    named_index_collection directions;
    int32_t current_state;
    int32_t current_direction;
    direction_angles *direction_parameters;
    bool *shown_layers;
    dir_state_data *shown_layers_by_dir_state;
    int32_t *shown_layer_cache;
} character_data;

typedef struct _character_data *character;

typedef enum { 
    GK_LABEL = 1,
    GK_BUTTON = 2,
    GK_CHECK_BOX = 4,
    GK_RADIO_GROUP = 8,
    GK_TEXT_BOX = 16,
    GK_LIST = 32,
    GK_ANY_KIND = 63
} guielement_kind;

typedef enum { 
    EK_CLICKED,
    EK_TEXT_ENTRY_ENDED,
    EK_SELECTION_MADE
} event_kind;

typedef struct _guilist_data *guilist;

typedef struct _guilist_item { 
    const char *text;
    bitmap_cell image;
    guilist parent;
} guilist_item;

typedef struct _guilist_data { 
    bool vertical_scroll;
    rectangle scroll_up;
    rectangle scroll_down;
    rectangle scroll_area;
    int32_t columns;
    int32_t rows;
    int32_t row_height;
    int32_t col_width;
    int32_t scroll_size;
    rectangle *placeholder;
    int32_t active_item;
    int32_t starting_at;
    font_data *font;
    guilist_item *items;
    bitmap_data *scroll_button;
    font_alignment alignment;
} guilist_data;

typedef struct _guilabel_data { 
    const char *content_string;
    font_data *font;
    font_alignment alignment;
} guilabel_data;

typedef struct _guilabel_data *guilabel;

typedef struct _guicheckbox_data { 
    bool state;
} guicheckbox_data;

typedef struct _guicheckbox_data *guicheckbox;

typedef enum { 
    FD_FILES = 1,
    FD_DIRECTORIES = 2,
    FD_FILES_AND_DIRECTORIES = 3
} file_dialog_select_type;

typedef struct _panel_data *panel;

typedef struct _region_data *region;

typedef struct _guitextbox_data *guitextbox;

typedef void *guievent_callback;

typedef struct _region_data { 
    const char *string_id;
    guielement_kind kind;
    int32_t region_idx;
    int32_t element_index;
    rectangle area;
    bool active;
    panel parent;
    guievent_callback *callbacks;
} region_data;

typedef struct _guiradio_group_data { 
    const char *group_id;
    region **buttons;
    int32_t active_button;
} guiradio_group_data;

typedef struct _guiradio_group_data *guiradio_group;

typedef struct _guitextbox_data { 
    const char *content_string;
    font_data *font;
    int32_t length_limit;
    region for_region;
    font_alignment alignment;
} guitextbox_data;

typedef struct _panel_data { 
    const char *name;
    const char *filename;
    int32_t panel_id;
    rectangle area;
    bool visible;
    bool active;
    bool draggable;
    bitmap_data *panel_bitmap;
    bitmap_data *panel_bitmap_inactive;
    bitmap_data *panel_bitmap_active;
    region_data *regions;
    named_index_collection region_ids;
    guilabel_data *labels;
    guicheckbox_data *check_boxes;
    guiradio_group_data *radio_groups;
    guitextbox_data *text_boxes;
    guilist_data *lists;
    bool modal;
    bool draw_as_vectors;
} panel_data;

typedef struct _message_ptr { 
} message_ptr;

typedef struct _message_link { 
    const char *data;
    struct _message_link *prev;
    struct _message_link *next;
} message_link;

typedef struct _connection_data { 
    void *socket;
    uint32_t ip;
    int32_t port;
    struct _message_link *first_msg;
    struct _message_link *last_msg;
    int32_t msg_count;
    bool is_tcp;
    int32_t msg_len;
    const char *part_msg_data;
} connection_data;

typedef struct _connection_data *connection;

typedef struct _arduino_data { 
    const char *name;
    void *ptr;
    const char *port;
    int32_t baud;
    bool open;
    bool has_error;
    const char *error_message;
} arduino_data;

typedef struct _arduino_device_data *arduino_device;


#ifdef __cplusplus
// C++ overloaded functions

#endif

#endif

